// Serialize React Flow graph → .claude-plugin/ directory structure
// This is the core spike question: can we go from graph → valid plugin?

import type { Node, Edge } from '@xyflow/react';
import type { RuleData, HookData, SkillData, CommandData, AgentData, PluginNodeType } from './types';

export interface PluginFile {
  path: string;
  content: string;
}

export interface SerializationResult {
  files: PluginFile[];
  errors: string[];
}

export function serializeGraph(nodes: Node[], edges: Edge[]): SerializationResult {
  const files: PluginFile[] = [];
  const errors: string[] = [];

  // plugin.json manifest
  files.push({
    path: 'plugin.json',
    content: JSON.stringify({
      name: 'my-plugin',
      version: '1.0.0',
      description: 'Generated by BotCamp',
      author: '',
    }, null, 2),
  });

  // Process each node by type
  for (const node of nodes) {
    const type = node.type as PluginNodeType;

    switch (type) {
      case 'rule': {
        const d = node.data as unknown as RuleData;
        if (!d.name) { errors.push(`Rule node ${node.id} has no name`); continue; }

        let content = '';
        if (d.pathFilter) {
          content += `---\npaths:\n  - "${d.pathFilter}"\n---\n\n`;
        }
        content += d.content || '# ' + d.name;

        files.push({ path: `rules/${d.name}.md`, content });
        break;
      }

      case 'skill': {
        const d = node.data as unknown as SkillData;
        if (!d.name) { errors.push(`Skill node ${node.id} has no name`); continue; }

        const frontmatter: Record<string, string> = {};
        if (d.description) frontmatter.description = d.description;
        if (d.filePattern) frontmatter.filePattern = d.filePattern;
        if (d.bashPattern) frontmatter.bashPattern = d.bashPattern;

        let content = '---\n';
        for (const [k, v] of Object.entries(frontmatter)) {
          content += `${k}: "${v}"\n`;
        }
        content += '---\n\n';
        content += d.instructions || '# ' + d.name;

        files.push({ path: `skills/${d.name}/SKILL.md`, content });
        break;
      }

      case 'command': {
        const d = node.data as unknown as CommandData;
        if (!d.name) { errors.push(`Command node ${node.id} has no name`); continue; }
        files.push({ path: `commands/${d.name}.md`, content: d.prompt || '# ' + d.name });
        break;
      }

      case 'agent': {
        const d = node.data as unknown as AgentData;
        if (!d.name) { errors.push(`Agent node ${node.id} has no name`); continue; }

        let content = `# ${d.name}\n\n`;
        if (d.model) content += `**Model:** ${d.model}\n\n`;
        if (d.systemPrompt) content += `## System Prompt\n\n${d.systemPrompt}\n\n`;
        if (d.allowedTools?.length) content += `## Allowed Tools\n\n${d.allowedTools.map(t => `- ${t}`).join('\n')}\n`;

        files.push({ path: `agents/${d.name}.md`, content });
        break;
      }

      case 'hook':
        // Hooks are collected into hooks.json below
        break;
    }
  }

  // Collect all hook nodes into hooks/hooks.json
  const hookNodes = nodes.filter(n => n.type === 'hook');
  if (hookNodes.length > 0) {
    const hooksConfig: Record<string, Array<{ matcher: string; hooks: Array<{ type: string; command: string }> }>> = {};

    for (const hookNode of hookNodes) {
      const d = hookNode.data as unknown as HookData;
      const event = d.event || 'PreToolUse';

      if (!hooksConfig[event]) hooksConfig[event] = [];

      // Find what this hook connects to (for the action)
      const connectedEdges = edges.filter(e => e.source === hookNode.id);
      const targetNodes = connectedEdges
        .map(e => nodes.find(n => n.id === e.target))
        .filter(Boolean);

      let action = d.action || '';
      if (!action && targetNodes.length > 0) {
        // Auto-generate action from connected rule/skill
        const target = targetNodes[0]!;
        if (target.type === 'rule') {
          const rd = target.data as unknown as RuleData;
          action = `cat "\${CLAUDE_PLUGIN_ROOT}/rules/${rd.name}.md"`;
        } else if (target.type === 'skill') {
          const sd = target.data as unknown as SkillData;
          action = `cat "\${CLAUDE_PLUGIN_ROOT}/skills/${sd.name}/SKILL.md"`;
        }
      }

      const hookEntry: { matcher: string; hooks: Array<{ type: string; command: string }> } = {
        matcher: d.matcher || '.*',
        hooks: [{ type: 'command', command: action }],
      };

      hooksConfig[event].push(hookEntry);
    }

    files.push({
      path: 'hooks/hooks.json',
      content: JSON.stringify(hooksConfig, null, 2),
    });
  }

  return { files, errors };
}

// Pretty-print the file tree
export function formatFileTree(files: PluginFile[]): string {
  const lines = ['.claude-plugin/'];
  const sorted = [...files].sort((a, b) => a.path.localeCompare(b.path));

  for (const file of sorted) {
    const parts = file.path.split('/');
    const indent = '  '.repeat(parts.length);
    lines.push(`${indent}${parts[parts.length - 1]}`);
  }

  return lines.join('\n');
}
