// GitHub API integration for exporting plugins to repos
// Uses the Git Data API for atomic multi-file commits

import type { PluginFile } from './serialize';

interface GitHubTreeItem {
  path: string;
  mode: '100644';
  type: 'blob';
  content: string;
}

export async function createRepoAndPush(
  accessToken: string,
  repoName: string,
  description: string,
  files: PluginFile[],
): Promise<{ repoUrl: string; error?: string }> {
  const headers = {
    Authorization: `Bearer ${accessToken}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };

  // Step 1: Create repository
  const createRepoRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: repoName,
      description,
      auto_init: true, // creates initial commit with README
      private: false,
    }),
  });

  if (!createRepoRes.ok) {
    const err = await createRepoRes.json();
    if (createRepoRes.status === 422 && err.errors?.some((e: { message: string }) => e.message === 'name already exists on this account')) {
      return { repoUrl: '', error: `Repository "${repoName}" already exists. Choose a different name.` };
    }
    return { repoUrl: '', error: `Failed to create repo: ${err.message}` };
  }

  const repo = await createRepoRes.json();
  const owner = repo.owner.login;
  const fullName = `${owner}/${repoName}`;

  // Step 2: Get the default branch ref (main)
  const refRes = await fetch(`https://api.github.com/repos/${fullName}/git/ref/heads/main`, { headers });
  if (!refRes.ok) {
    return { repoUrl: repo.html_url, error: 'Repo created but failed to get branch ref' };
  }
  const ref = await refRes.json();
  const baseCommitSha = ref.object.sha;

  // Step 3: Get the base commit's tree
  const commitRes = await fetch(`https://api.github.com/repos/${fullName}/git/commits/${baseCommitSha}`, { headers });
  const commit = await commitRes.json();
  const baseTreeSha = commit.tree.sha;

  // Step 4: Create a new tree with all plugin files
  const tree: GitHubTreeItem[] = files.map(f => ({
    path: `.claude-plugin/${f.path}`,
    mode: '100644' as const,
    type: 'blob' as const,
    content: f.content,
  }));

  // Add a README
  tree.push({
    path: 'README.md',
    mode: '100644',
    type: 'blob',
    content: `# ${repoName}\n\n${description}\n\nGenerated by [AI Team Builder](https://jfritz.xyz/ai-team-builder) — the visual Claude Code plugin builder.\n\n## Install\n\n\`\`\`bash\nclaude plugin add ${fullName}\n\`\`\`\n`,
  });

  const treeRes = await fetch(`https://api.github.com/repos/${fullName}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ base_tree: baseTreeSha, tree }),
  });

  if (!treeRes.ok) {
    return { repoUrl: repo.html_url, error: 'Failed to create file tree' };
  }
  const newTree = await treeRes.json();

  // Step 5: Create a commit
  const newCommitRes = await fetch(`https://api.github.com/repos/${fullName}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      message: 'Initial plugin export from AI Team Builder',
      tree: newTree.sha,
      parents: [baseCommitSha],
    }),
  });

  if (!newCommitRes.ok) {
    return { repoUrl: repo.html_url, error: 'Failed to create commit' };
  }
  const newCommit = await newCommitRes.json();

  // Step 6: Update the branch ref
  const updateRefRes = await fetch(`https://api.github.com/repos/${fullName}/git/refs/heads/main`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({ sha: newCommit.sha }),
  });

  if (!updateRefRes.ok) {
    return { repoUrl: repo.html_url, error: 'Failed to update branch' };
  }

  return { repoUrl: repo.html_url };
}

export function generateMcpbBundle(files: PluginFile[], pluginName: string): Blob {
  // MCPB is a ZIP file — for MVP, we'll create a simple downloadable archive
  // In production, use JSZip or similar
  const manifest = {
    name: pluginName,
    version: '1.0.0',
    type: 'claude-plugin',
    files: files.map(f => f.path),
  };

  // For now, return the file list as JSON (proper ZIP generation requires JSZip)
  const content = JSON.stringify({ manifest, files }, null, 2);
  return new Blob([content], { type: 'application/json' });
}
